export const eventTypesList = [
    { "eventTypeId": 4, "marketCount": 22, "name": "Cricket" },
    { "eventTypeId": 1, "marketCount": 701, "name": "Football" },
    { "eventTypeId": 2, "marketCount": 137, "name": "Tennis" },
    { "eventTypeId": 7522, "marketCount": 114, "name": "Basketball" },
    { "eventTypeId": 27454571, "marketCount": 92, "name": "Esports" },
    { "eventTypeId": 3503, "marketCount": 19, "name": "Darts" },
    { "eventTypeId": 998917, "marketCount": 1, "name": "Volleyball" },
    { "eventTypeId": 2152880, "marketCount": 14, "name": "Gaelic Games" },
    { "eventTypeId": 26420387, "marketCount": 21, "name": "Mixed Martial Arts" },
    { "eventTypeId": 'str_2', "marketCount": 0, "name": "Horse Racing" },
    { "eventTypeId": 'str_11', "marketCount": 0, "name": "Horse Racing - Today's Card" },
    { "eventTypeId": 'str_3', "marketCount": 0, "name": "Greyhound Racing" },
    { "eventTypeId": 'str_10', "marketCount": 0, "name": "Greyhounds - Today's Card" },
    { "eventTypeId": 'str_4', "marketCount": 0, "name": "Politics" },
    { "eventTypeId": 5, "marketCount": 28, "name": "Rugby Union" },
    { "eventTypeId": 1477, "marketCount": 12, "name": "Rugby League" },
    { "eventTypeId": 6, "marketCount": 47, "name": "Boxing" },
    { "eventTypeId": 7511, "marketCount": 10, "name": "Baseball" },
    { "eventTypeId": 'str_6', "marketCount": 0, "name": "Golf" },
    { "eventTypeId": 'str_9', "marketCount": 0, "name": "Motor Sport" },
    // { "eventTypeId": 'str_7', "marketCount": 0, "name": "Winter Sports" },
    // { "eventTypeId": 'str_1', "marketCount": 0, "name": "Snooker" },
    // { "eventTypeId": 468328, "marketCount": 14, "name": "Handball" },
    // { "eventTypeId": 61420, "marketCount": 13, "name": "Australian Rules" },
    // { "eventTypeId": 'str_5', "marketCount": 0, "name": "Cycling" },
    // { "eventTypeId": 'str_8', "marketCount": 0, "name": "American Football" },
    // { "eventTypeId": 7524, "marketCount": 39, "name": "Ice Hockey" },
]
